apiVersion: v1
kind: Service
metadata:
  labels:
    app: flink
    component: jobmanager
  name: flink-jobmanager-lb
spec:
  ports:
  - name: rpc
    port: 6123
    protocol: TCP
    targetPort: 6123
  - name: webui
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: blob
    port: 6124
    protocol: TCP
    targetPort: 6124
  selector:
    app: flink
    component: jobmanager
  type: LoadBalancer