apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: bigquery-key
      containers:
      - name: taskmanager
        image: flink:1.5.0
        args:
        - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: <loadbalancer-IP>
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json

