version: "2.1"
services:
  jobmanager:
    image: flink:1.5.0
    expose:
      - "6123"
    ports:
      - "8081:8081"
      - "6123:6123"
    volumes:
      - /Users/michael/projekte/ase-ss18/code/keys/:/keys/
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/MichaelHoeller-2a0caf6d0c59.json

  taskmanager:
    image: flink:1.5.0
    expose:
      - "6121"
      - "6122"
    volumes:
      - /Users/michael/projekte/ase-ss18/code/keys/:/keys/
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/MichaelHoeller-2a0caf6d0c59.json

